name: Basic Continuous Integration

on: [push]

jobs:
  phpunit-unit:
    name: PHPUnit Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: intl
          tools: composer:v1

      - name: Cache Composer packages
        uses: actions/cache@v2
        with:
          path: /home/runner/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies
        run: composer install --dev --no-interaction --no-progress

      - name: Execute Unit tests
        run: vendor/bin/phpunit test
